server {
  listen 80;
  listen [::]:80;
  server_name wuxia.drowts.cn;

  root /www/wwwroot/wuxia-idle/current;
  index index.html;

  access_log /var/log/nginx/wuxia-idle.access.log;
  error_log /var/log/nginx/wuxia-idle.error.log warn;

  location ^~ /.well-known/acme-challenge/ {
    root /www/wwwroot/wuxia-idle/acme;
    default_type text/plain;
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
